services:
  latex:
    image: registry.gitlab.com/islandoftex/images/texlive:latest
    container_name: latex-docker-template
    working_dir: /workdir
    volumes:
      - .:/workdir
    command: tail -f /dev/null
